name: Meson Build
description: Builds Rofi using Meson

inputs:
  cc:
    description: Compiler to use
    required: true
  xcb:
    description: Enable xcb backend
    default: enabled
  wayland:
    description: Enable wayland backend
    default: enabled

runs:
  using: composite
  steps:
    - id: pip
      run: pip install git+https://github.com/mesonbuild/meson@e58b3adc7044980bbddca1ad9674ac7b0c5bac0a ninja
      shell: bash
    - id: setup
      run: meson setup builddir -Dxcb=${{ inputs.xcb }} -Dwayland=${{ inputs.wayland }}
      shell: bash
      env:
        CC: ${{ inputs.cc }}
    - id: build
      run: ninja -C builddir
      shell: bash
    - id: dist
      run: ninja -C builddir dist
      shell: bash
    - id: test
      run: ninja -C builddir test
      shell: bash
    - id: doxy
      run: ninja -C builddir doc/html > doxygen.log 2>&1 
      shell: bash
    - id: doxycheck
      uses: ./.github/actions/doxycheck
      with:
        logfile: doxygen.log
